using System;
using System.Collections.Generic;
using System.IO;
using Rhino.Geometry;

namespace RhinoToMinecraft.Core;

/// <summary>
/// Pure logic for Slice 4: formats resolved voxels as Minecraft "/setblock"
/// commands and writes them to a .mcfunction text file. Converts Rhino's Z-up
/// coordinate space to Minecraft's Y-up space (Y and Z swap places, with Y
/// negated to preserve handedness - both Rhino and Minecraft are right-handed,
/// and a bare two-axis swap would otherwise mirror the model) and applies a
/// configurable world-origin offset in Minecraft's coordinate space.
/// </summary>
public static class McFunctionExporter
{
    public static IEnumerable<string> BuildCommands(
        IReadOnlyList<(Point3d Position, string BlockId)> voxels,
        Point3d originOffset)
    {
        foreach (var (position, blockId) in voxels)
        {
            // Block-space positions sit at a half-integer offset (e.g. 2.5) per
            // issue 07, so the containing block is found by flooring, not
            // rounding. Rhino is Z-up; Minecraft is Y-up, so Rhino's Y and Z swap
            // places - but a straight swap of two axes flips handedness (Rhino
            // and Minecraft are both right-handed), which mirrors the model.
            // Negating Y before flooring restores a proper rotation instead of a
            // reflection.
            int x = (int)Math.Floor(position.X) + (int)Math.Round(originOffset.X);
            int y = (int)Math.Floor(position.Z) + (int)Math.Round(originOffset.Y);
            int z = (int)Math.Floor(-position.Y) + (int)Math.Round(originOffset.Z);
            yield return $"setblock {x} {y} {z} {blockId}";
        }
    }

    public static int WriteFile(
        string path,
        IReadOnlyList<(Point3d Position, string BlockId)> voxels,
        Point3d originOffset)
    {
        var commands = new List<string>(BuildCommands(voxels, originOffset));
        File.WriteAllLines(path, commands);
        return commands.Count;
    }

    /// <summary>
    /// Slice 9: writes the resolved voxels directly into a world save's datapack
    /// folder structure (<paramref name="worldSaveFolder"/>/datapacks/<paramref name="packName"/>/data/<paramref name="namespace"/>/functions/<paramref name="functionName"/>.mcfunction),
    /// creating a minimal pack.mcmeta if one doesn't already exist there, so the
    /// result is recognized by Minecraft after an in-game `/reload` without any
    /// manual file placement. Does not trigger `/reload` or `/function` itself -
    /// a singleplayer save has no RCON/server console for an external tool to
    /// call, so running the function in-game remains a manual step.
    /// </summary>
    public static (string FilePath, int CommandCount) WriteToWorld(
        string worldSaveFolder,
        string packName,
        string @namespace,
        string functionName,
        IReadOnlyList<(Point3d Position, string BlockId)> voxels,
        Point3d originOffset,
        int packFormat = 41)
    {
        string packFolder = Path.Combine(worldSaveFolder, "datapacks", packName);
        Directory.CreateDirectory(packFolder);

        string mcmetaPath = Path.Combine(packFolder, "pack.mcmeta");
        if (!File.Exists(mcmetaPath))
        {
            string mcmeta = "{\n  \"pack\": {\n    \"pack_format\": " + packFormat + ",\n    \"description\": \"Generated by RhinoToMinecraft\"\n  }\n}\n";
            File.WriteAllText(mcmetaPath, mcmeta);
        }

        string functionsFolder = Path.Combine(packFolder, "data", @namespace, "functions");
        Directory.CreateDirectory(functionsFolder);

        string functionPath = Path.Combine(functionsFolder, functionName + ".mcfunction");
        int count = WriteFile(functionPath, voxels, originOffset);

        return (functionPath, count);
    }
}
